### ISSUE TITLE
Afraid!

### ISSUE THREAD

**Issue by ssfdust** [xuqix/opengl-toy#1]
What is it？

**Comment by xuqix** [comment]
@ssfdust 
I dont know, just think of what to write

**Comment by ssfdust** [comment]
zhe ge dong xi hai you anything else ma?zhe shi yi jing give up le ma

**Comment by xuqix** [comment]
@ssfdust 
yi jing give up le

**Comment by ssfdust** [comment]
jiu hen sad

_Sent from my OnePlus ONEPLUS A3000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
